all:
	@make -C src
	@cp src/aes .

clean:
	@rm -f src/*.o aes src/aes
random:
	gcc --help
help:
	@echo "Usage: "
	@echo "make \t Build the software"
	@echo "make clean\t Remove all files generated by make"
	@echo "make test\t Execute testing script (tester.sh in tests folder)"
	@echo "make help\t Display this help"
	@echo "make report\t Create the pdf for the report of the project"


.PHONY: all clean test report help
