SHELL := /bin/bash

all:
	@make -C src
	@cp src/aes .

clean:
	@rm -f src/*.o aes src/aes
random:
	gcc --help
help:
	@echo "Usage: "
	@echo "make Build the software"
	@echo "make clean Remove all files generated by make"
	@echo "make test Execute testing script "
	@echo "make help Display this help"

test:
	@chmod u+x ./test.sh
	@time ./test.sh


.PHONY: all clean test help
